import { router, useLocalSearchParams } from "expo-router";
import { useEffect, useState } from "react";
import { Pressable, StyleSheet, Switch, Text, View } from "react-native";
import { Brand, Button, ChoiceGroup, Field, InlineMessage, PageTitle, Panel, Screen } from "@/components/garage-ui";
import { localDateToday, nativeSymptomSchema } from "@/lib/record-validation";
import { supabase } from "@/lib/supabase";
import { useSession } from "@/providers/session-provider";
import { usePalette } from "@/theme";

type Severity="low"|"medium"|"high";type Frequency="once"|"intermittent"|"constant";
export default function NewSymptomScreen(){
  const {id}=useLocalSearchParams<{id:string}>();const {session}=useSession();const p=usePalette();const [title,setTitle]=useState("");const [firstNoticed,setFirstNoticed]=useState(localDateToday());const [mileage,setMileage]=useState("");const [severity,setSeverity]=useState<Severity>("medium");const [frequency,setFrequency]=useState<Frequency>("intermittent");const [description,setDescription]=useState("");const [warningLight,setWarningLight]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState<{text:string;error?:boolean}>();
  useEffect(()=>{if(!id)return;void supabase.from("vehicles").select("current_mileage").eq("id",id).maybeSingle().then(({data})=>{if(data)setMileage(String(data.current_mileage))})},[id]);
  async function save(){if(!session||!id)return;const parsed=nativeSymptomSchema.safeParse({title,firstNoticed,mileage,severity,frequency,description,warningLight});if(!parsed.success){setMessage({text:parsed.error.issues[0]?.message??"Check the symptom details.",error:true});return}setBusy(true);setMessage(undefined);const value=parsed.data;const {error}=await supabase.from("symptoms").insert({owner_id:session.user.id,vehicle_id:id,title:value.title,description:value.description,severity:value.severity,frequency:value.frequency,status:"open",warning_light:value.warningLight,first_noticed_at:value.firstNoticed,mileage:value.mileage});if(error){setMessage({text:"The symptom could not be saved. Check your connection and try again.",error:true});setBusy(false);return}router.replace(`/vehicles/${id}`)}
  return <Screen><View style={styles.top}><Brand/><Pressable accessibilityRole="button" onPress={()=>router.back()}><Text style={[styles.cancel,{color:p.teal}]}>Cancel</Text></Pressable></View><PageTitle subtitle="Capture what you observe before a repair. OTTOKO records the problem without attempting to diagnose it.">Log a symptom</PageTitle><Panel>{message?<InlineMessage error={message.error}>{message.text}</InlineMessage>:null}<Field label="What’s happening?" autoCapitalize="sentences" value={title} onChangeText={setTitle}/><View style={styles.row}><View style={styles.half}><Field label="First noticed" autoCapitalize="none" placeholder="YYYY-MM-DD" value={firstNoticed} onChangeText={setFirstNoticed}/></View><View style={styles.half}><Field label="Mileage" keyboardType="number-pad" value={mileage} onChangeText={setMileage}/></View></View><ChoiceGroup label="Severity" value={severity} onChange={value=>setSeverity(value as Severity)} options={[{label:"Low",value:"low"},{label:"Medium",value:"medium"},{label:"High",value:"high"}]}/><ChoiceGroup label="Frequency" value={frequency} onChange={value=>setFrequency(value as Frequency)} options={[{label:"Once",value:"once"},{label:"Intermittent",value:"intermittent"},{label:"Constant",value:"constant"}]}/><Field label="Describe the symptom" multiline placeholder="What did you notice, and under what conditions?" value={description} onChangeText={setDescription}/><View style={[styles.switchRow,{borderColor:p.border}]}><View style={styles.flex}><Text style={[styles.switchTitle,{color:p.text}]}>Dashboard warning light</Text><Text style={[styles.switchCopy,{color:p.muted}]}>Turn on only if a warning light appeared with this symptom.</Text></View><Switch accessibilityLabel="A dashboard warning light appeared" value={warningLight} onValueChange={setWarningLight} trackColor={{false:p.surface,true:p.amber}} thumbColor={warningLight?"#191c1d":p.muted}/></View><Button busy={busy} onPress={save}>Log symptom</Button></Panel></Screen>;
}
const styles=StyleSheet.create({top:{flexDirection:"row",alignItems:"center",justifyContent:"space-between"},cancel:{fontSize:13,fontWeight:"800",paddingVertical:10},row:{flexDirection:"row",gap:12},half:{flex:1},switchRow:{flexDirection:"row",alignItems:"center",gap:16,borderWidth:1,borderRadius:12,padding:14,marginBottom:16},flex:{flex:1},switchTitle:{fontSize:13,fontWeight:"800"},switchCopy:{fontSize:12,lineHeight:18,marginTop:3}});
