"use client";
import Link from "next/link";
import { useActionState } from "react";
import { login, signup, type AuthState } from "@/app/auth/actions";
import { Brand } from "./brand";
import { ResendConfirmationForm } from "./resend-confirmation-form";
import { CheckCircle2, FileText, Wrench } from "lucide-react";

const initialState: AuthState = {};
export function AuthCard({ mode, nextPath, initialError }: { mode: "login" | "signup"; nextPath?:string; initialError?:string }) {
  const isSignup = mode === "signup"; const [state, action, pending] = useActionState(isSignup ? signup : login, initialState);
  return <main className="auth-shell"><section className="auth-story" aria-label="GarageBook benefits"><div><Brand/><p className="auth-kicker">The complete service record</p><h1>Know what happened.<br/>Know what comes next.</h1><p>Keep the evidence behind every symptom, shop visit, repair, invoice, and reminder in one dependable place.</p><ul><li><CheckCircle2 size={17}/>A history you control</li><li><Wrench size={17}/>The full repair journey</li><li><FileText size={17}/>Receipts and photos together</li></ul></div></section><div className="auth-panel"><div className="auth-mobile-brand"><Brand/></div><div className="auth-card-stack"><section className="auth-card"><p className="page-eyebrow">{isSignup?"Start your garage":"Your garage is waiting"}</p><h2>{isSignup ? "Create your GarageBook" : "Welcome back"}</h2><p className="auth-card-intro">{isSignup ? "Start building a trusted history for your vehicles." : "Sign in to continue to your garage."}</p>{initialError&&<p className="mt-5 rounded-lg bg-red-50 p-3 text-sm text-red-700" role="alert">{initialError}</p>}<form action={action} className="mt-7 space-y-4">{nextPath&&<input name="next" type="hidden" value={nextPath}/>} {isSignup && <div className="field"><label htmlFor="fullName">Full name</label><input id="fullName" name="fullName" autoComplete="name" required /></div>}<div className="field"><label htmlFor="email">Email address</label><input id="email" name="email" type="email" autoComplete="email" required /></div><div className="field"><div className="flex items-center justify-between gap-3"><label htmlFor="password">Password</label>{!isSignup&&<Link className="text-xs font-semibold text-teal" href="/forgot-password">Forgot password?</Link>}</div><input id="password" name="password" type="password" minLength={8} autoComplete={isSignup ? "new-password" : "current-password"} required /></div>{state.error && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-700" role="alert">{state.error}</p>}{state.message && <p className="rounded-lg bg-[#e4f4ed] p-3 text-sm text-[#146449]" role="status">{state.message}</p>}<button className="btn btn-primary btn-lg mt-2 w-full" disabled={pending}>{pending ? "Please wait…" : isSignup ? "Create account" : "Log in"}</button></form><p className="mt-6 text-center text-sm text-muted">{isSignup ? "Already have an account? " : "New to GarageBook? "}<Link className="font-semibold text-teal" href={isSignup ? "/login" : "/signup"}>{isSignup ? "Log in" : "Create account"}</Link></p></section>{isSignup&&<ResendConfirmationForm/>}</div></div></main>;
}
