"use client";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { z } from "zod";

const vehicleSchema=z.object({year:z.coerce.number().min(1886).max(new Date().getFullYear()+1),make:z.string().min(2,"Enter the manufacturer"),model:z.string().min(1,"Enter the model"),trim:z.string().optional(),mileage:z.coerce.number().min(0,"Mileage cannot be negative"),vin:z.string().length(17,"VIN must be 17 characters").or(z.literal("")),color:z.string().optional()});
type VehicleFields=z.infer<typeof vehicleSchema>;
export function VehicleForm(){const {register,handleSubmit,formState:{errors,isSubmitting,isSubmitSuccessful}}=useForm<VehicleFields>({resolver:zodResolver(vehicleSchema),defaultValues:{year:2014,make:"MINI",model:"Cooper S Paceman",trim:"ALL4",mileage:121450,vin:"",color:"Oxford Green"}});return <FormFrame success={isSubmitSuccessful} successText="Vehicle draft saved for preview."><form className="grid gap-5 sm:grid-cols-2" onSubmit={handleSubmit(async()=>{await Promise.resolve()})}><Field label="Model year" error={errors.year?.message}><input type="number" {...register("year")}/></Field><Field label="Make" error={errors.make?.message}><input {...register("make")}/></Field><Field label="Model" error={errors.model?.message}><input {...register("model")}/></Field><Field label="Trim"><input {...register("trim")}/></Field><Field label="Current mileage" error={errors.mileage?.message}><input type="number" {...register("mileage")}/></Field><Field label="Exterior color"><input {...register("color")}/></Field><div className="sm:col-span-2"><Field label="VIN (optional)" error={errors.vin?.message}><input maxLength={17} placeholder="17-character vehicle identification number" {...register("vin")}/></Field></div><FormActions busy={isSubmitting} label="Add vehicle"/></form></FormFrame>}

const maintenanceSchema=z.object({type:z.enum(["maintenance","repair","inspection"]),title:z.string().min(3,"Describe the service performed"),date:z.string().min(1,"Choose a date"),mileage:z.coerce.number().min(1),shop:z.string().optional(),cost:z.coerce.number().min(0),notes:z.string().min(5,"Add a brief service note")});type MaintenanceFields=z.infer<typeof maintenanceSchema>;
export function MaintenanceForm(){const {register,handleSubmit,formState:{errors,isSubmitting,isSubmitSuccessful}}=useForm<MaintenanceFields>({resolver:zodResolver(maintenanceSchema),defaultValues:{type:"repair",title:"",date:"2026-08-08",mileage:121450,shop:"North Loop Motorworks",cost:0,notes:""}});return <FormFrame success={isSubmitSuccessful} successText="Maintenance record saved for preview."><form className="grid gap-5 sm:grid-cols-2" onSubmit={handleSubmit(async()=>{await Promise.resolve()})}><Field label="Record type"><select {...register("type")}><option value="maintenance">Maintenance</option><option value="repair">Repair</option><option value="inspection">Inspection</option></select></Field><Field label="Service date" error={errors.date?.message}><input type="date" {...register("date")}/></Field><div className="sm:col-span-2"><Field label="Service or repair" error={errors.title?.message}><input placeholder="e.g. Front brake pad replacement" {...register("title")}/></Field></div><Field label="Mileage" error={errors.mileage?.message}><input type="number" {...register("mileage")}/></Field><Field label="Total cost" error={errors.cost?.message}><input min="0" step="0.01" type="number" {...register("cost")}/></Field><div className="sm:col-span-2"><Field label="Repair shop"><input {...register("shop")}/></Field></div><div className="sm:col-span-2"><Field label="Work performed" error={errors.notes?.message}><textarea placeholder="What was inspected, repaired, or replaced?" {...register("notes")}/></Field></div><FormActions busy={isSubmitting} label="Save maintenance record"/></form></FormFrame>}

const symptomSchema=z.object({title:z.string().min(3,"Describe the problem"),firstNoticed:z.string().min(1),mileage:z.coerce.number().min(1),severity:z.enum(["low","medium","high"]),frequency:z.enum(["once","intermittent","constant"]),description:z.string().min(10,"Add a little more detail"),warningLight:z.boolean()});type SymptomFields=z.infer<typeof symptomSchema>;
export function SymptomForm(){const {register,handleSubmit,formState:{errors,isSubmitting,isSubmitSuccessful}}=useForm<SymptomFields>({resolver:zodResolver(symptomSchema),defaultValues:{title:"Intermittent oil-pressure warning",firstNoticed:"2026-08-08",mileage:121450,severity:"medium",frequency:"intermittent",description:"Warning appears briefly at warm idle and clears after engine speed increases.",warningLight:true}});return <FormFrame success={isSubmitSuccessful} successText="Symptom logged and added to the timeline."><form className="grid gap-5 sm:grid-cols-2" onSubmit={handleSubmit(async()=>{await Promise.resolve()})}><div className="sm:col-span-2"><Field label="What’s happening?" error={errors.title?.message}><input {...register("title")}/></Field></div><Field label="First noticed" error={errors.firstNoticed?.message}><input type="date" {...register("firstNoticed")}/></Field><Field label="Mileage" error={errors.mileage?.message}><input type="number" {...register("mileage")}/></Field><Field label="Severity"><select {...register("severity")}><option value="low">Low — monitor</option><option value="medium">Medium — schedule soon</option><option value="high">High — stop driving</option></select></Field><Field label="Frequency"><select {...register("frequency")}><option value="once">Happened once</option><option value="intermittent">Intermittent</option><option value="constant">Constant</option></select></Field><div className="sm:col-span-2"><Field label="Describe the symptom" error={errors.description?.message}><textarea {...register("description")}/></Field></div><label className="sm:col-span-2 flex items-center gap-3 rounded-xl border border-[#dde3df] p-4 text-sm font-medium"><input className="h-4 w-4 accent-[#087f75]" type="checkbox" {...register("warningLight")}/>A dashboard warning light appeared</label><FormActions busy={isSubmitting} label="Log symptom"/></form></FormFrame>}

function Field({label,error,children}:{label:string;error?:string;children:React.ReactNode}){return <div className="field"><label>{label}</label>{children}{error&&<p className="field-error" role="alert">{error}</p>}</div>}
function FormActions({busy,label}:{busy:boolean;label:string}){return <div className="flex justify-end gap-3 border-t border-[#edf0ed] pt-5 sm:col-span-2"><button className="btn btn-secondary" type="button">Cancel</button><button className="btn btn-primary" disabled={busy} type="submit">{busy?"Saving…":label}</button></div>}
function FormFrame({children,success,successText}:{children:React.ReactNode;success:boolean;successText:string}){return <div className="card p-5 sm:p-7">{success&&<div className="mb-5 rounded-xl bg-[#e4f4ed] p-4 text-sm font-medium text-[#146449]" role="status">{successText}</div>}{children}</div>}
