import { AlertCircle, FileText, Gauge, MapPin, Wrench } from "lucide-react";
import type { TimelineEvent, TimelineEventType } from "@/lib/types";
import { formatCurrency, formatDate, formatMileage } from "@/lib/sample-data";

const icons:Record<TimelineEventType,React.ComponentType<{size?:number}>>={maintenance:Wrench,repair:Wrench,symptom:AlertCircle,shop_visit:MapPin,mileage_update:Gauge,document_upload:FileText};
const labels:Record<TimelineEventType,string>={maintenance:"Maintenance",repair:"Repair",symptom:"Symptom",shop_visit:"Shop visit",mileage_update:"Mileage",document_upload:"Document"};
export function VehicleTimeline({events,compact=false}:{events:TimelineEvent[];compact?:boolean}){
  return <ol className="relative ml-3 border-l border-[#d9dfdb]">{events.map((event)=>{const Icon=icons[event.type];return <li className={compact?"mb-5 ml-7":"mb-8 ml-9"} key={event.id}><span className="absolute -left-[17px] grid h-8 w-8 place-items-center rounded-full border border-[#d7e3df] bg-[#e9f4f1] text-teal"><Icon size={15}/></span><article className={compact?"":"card p-5 sm:p-6"}><div className="flex flex-col justify-between gap-2 sm:flex-row"><div><div className="mb-1 flex flex-wrap items-center gap-2"><span className="text-[11px] font-bold uppercase tracking-[.12em] text-teal">{labels[event.type]}</span>{event.status==="open"&&<span className="status status-watch">Open</span>}{event.status==="monitoring"&&<span className="status status-watch">Monitoring</span>}</div><h3 className="font-semibold tracking-[-.01em]">{event.title}</h3></div><time className="shrink-0 text-sm text-muted" dateTime={event.date}>{formatDate(event.date)}</time></div>{!compact&&<p className="mt-3 text-sm leading-6 text-muted">{event.description}</p>}<div className="mt-3 flex flex-wrap gap-x-5 gap-y-1 text-xs text-muted">{event.mileage&&<span>{formatMileage(event.mileage)} miles</span>}{event.shop&&<span>{event.shop}</span>}{event.cost!==undefined&&<span className="font-semibold text-charcoal">{formatCurrency(event.cost)}</span>}</div></article></li>})}</ol>;
}
