import Link from "next/link";
import { AlertCircle, ExternalLink, FileText, Gauge, MapPin, Pencil, Wrench } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import type { TimelineEvent, TimelineEventType } from "@/lib/types";
import { formatCurrency, formatDate, formatMileage } from "@/lib/format";
import { SemanticIcon, type SemanticTone } from "./semantic-icon";

const icons:Record<TimelineEventType,LucideIcon>={maintenance:Wrench,repair:Wrench,symptom:AlertCircle,shop_visit:MapPin,mileage_update:Gauge,document_upload:FileText};
const labels:Record<TimelineEventType,string>={maintenance:"Maintenance",repair:"Repair",symptom:"Symptom",shop_visit:"Shop visit",mileage_update:"Mileage",document_upload:"Document"};
const tones:Record<TimelineEventType,SemanticTone>={maintenance:"service",repair:"complete",symptom:"attention",shop_visit:"neutral",mileage_update:"complete",document_upload:"document"};
export function VehicleTimeline({events,compact=false}:{events:TimelineEvent[];compact?:boolean}){
  return <ol className="vehicle-timeline">{events.map((event)=>{const Icon=icons[event.type];const ActionIcon=event.type==="document_upload"?ExternalLink:Pencil;return <li className={compact?"timeline-item timeline-item-compact":"timeline-item"} key={event.id}><SemanticIcon icon={Icon} size={15} tone={tones[event.type]}/><article className={compact?"timeline-entry":"card timeline-entry p-5 sm:p-6"}><div className="flex flex-col justify-between gap-2 sm:flex-row"><div><div className="mb-1 flex flex-wrap items-center gap-2"><span className={`timeline-label timeline-label-${tones[event.type]}`}>{labels[event.type]}</span>{event.status==="open"&&<span className="status status-watch">Open</span>}{event.status==="monitoring"&&<span className="status status-watch">Monitoring</span>}</div><h3 className="font-semibold tracking-[-.01em]">{event.title}</h3></div><time className="shrink-0 text-sm text-muted" dateTime={event.date}>{formatDate(event.date)}</time></div>{!compact&&<p className="mt-3 text-sm leading-6 text-muted">{event.description}</p>}<div className="mt-3 flex flex-wrap items-center gap-x-5 gap-y-2 text-xs text-muted">{event.mileage&&<span>{formatMileage(event.mileage)} miles</span>}{event.shop&&<span>{event.shop}</span>}{event.cost!==undefined&&<span className="font-semibold text-charcoal">{formatCurrency(event.cost)}</span>}{!compact&&event.href&&<Link className="ml-auto inline-flex min-h-10 items-center gap-1.5 font-semibold text-teal" href={event.href}><ActionIcon size={14}/>{event.actionLabel??"Open"}</Link>}</div></article></li>})}</ol>;
}
