import { useFocusEffect, router } from "expo-router";
import { useCallback, useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from "react-native";
import { Brand, Button, PageTitle, Panel, Screen } from "@/components/garage-ui";
import { supabase } from "@/lib/supabase";
import { usePalette } from "@/theme";
interface Vehicle{id:string;year:number;make:string;model:string;trim:string|null;current_mileage:number}
export default function GarageScreen(){const p=usePalette();const [vehicles,setVehicles]=useState<Vehicle[]>();const load=useCallback(async()=>{const {data}=await supabase.from("vehicles").select("id,year,make,model,trim,current_mileage").order("created_at");setVehicles(data??[])},[]);useFocusEffect(useCallback(()=>{void load()},[load]));return <Screen><Brand/><PageTitle subtitle="Every vehicle keeps its own private evidence, timeline, and repair journeys.">My garage</PageTitle>{!vehicles?<View style={styles.loading}><ActivityIndicator color={p.teal}/></View>:vehicles.length?vehicles.map(vehicle=><Pressable accessibilityRole="button" accessibilityLabel={`Open ${vehicle.year} ${vehicle.make} ${vehicle.model}`} key={vehicle.id} onPress={()=>router.push(`/vehicles/${vehicle.id}`)} style={styles.vehiclePress}><Panel><Text style={[styles.vehicleName,{color:p.text}]}>{vehicle.year} {vehicle.make} {vehicle.model}</Text><Text style={[styles.meta,{color:p.muted}]}>{vehicle.trim||"Vehicle record"}</Text><Text style={[styles.mileage,{color:p.teal}]}>{vehicle.current_mileage.toLocaleString()} miles</Text><Text style={[styles.open,{color:p.muted}]}>Open vehicle →</Text></Panel></Pressable>):<Panel><Text style={[styles.vehicleName,{color:p.text}]}>No vehicles yet</Text><Text style={[styles.meta,{color:p.muted}]}>Add the vehicle you want to start tracking.</Text><View style={styles.action}><Button onPress={()=>router.push("/onboarding")}>Add vehicle</Button></View></Panel>}</Screen>}
const styles=StyleSheet.create({loading:{minHeight:320,alignItems:"center",justifyContent:"center"},vehiclePress:{marginBottom:12},vehicleName:{fontSize:18,fontWeight:"800"},meta:{fontSize:13,marginTop:5},mileage:{fontSize:14,fontWeight:"700",marginTop:14},open:{fontSize:12,fontWeight:"700",marginTop:14},action:{marginTop:18}});
