import { Image } from "expo-image";
import { useFocusEffect, router } from "expo-router";
import { useCallback, useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from "react-native";
import { Brand, Button, Divider, PageTitle, Panel, Screen, Stat } from "@/components/garage-ui";
import { supabase } from "@/lib/supabase";
import { useSession } from "@/providers/session-provider";
import { usePalette } from "@/theme";

interface DashboardData{vehicle:{id:string;year:number;make:string;model:string;trim:string|null;current_mileage:number}|null;photoUrl:string|null;maintenanceCount:number;openSymptoms:number;pendingReminders:number;recentMaintenance:{id:string;title:string;performed_at:string;cost:number|null}[]}
export default function DashboardScreen(){const {session}=useSession();const p=usePalette();const [data,setData]=useState<DashboardData>();const [error,setError]=useState<string>();
  const load=useCallback(async()=>{if(!session)return;setError(undefined);const vehicleResult=await supabase.from("vehicles").select("id,year,make,model,trim,current_mileage").order("created_at").limit(1).maybeSingle();if(vehicleResult.error){setError("Your garage could not be loaded. Pull back here and try again.");return}const vehicle=vehicleResult.data;if(!vehicle){setData({vehicle:null,photoUrl:null,maintenanceCount:0,openSymptoms:0,pendingReminders:0,recentMaintenance:[]});return}const [maintenance,symptoms,reminders,photo]=await Promise.all([supabase.from("maintenance_records").select("id,title,performed_at,cost",{count:"exact"}).eq("vehicle_id",vehicle.id).order("performed_at",{ascending:false}).limit(3),supabase.from("symptoms").select("id",{count:"exact",head:true}).eq("vehicle_id",vehicle.id).neq("status","resolved"),supabase.from("reminders").select("id",{count:"exact",head:true}).eq("vehicle_id",vehicle.id).eq("status","pending"),supabase.from("documents").select("storage_path").eq("vehicle_id",vehicle.id).eq("document_type","photo").is("repair_case_id",null).order("uploaded_at",{ascending:false}).limit(1).maybeSingle()]);let photoUrl:string|null=null;if(photo.data?.storage_path){const signed=await supabase.storage.from("vehicle-documents").createSignedUrl(photo.data.storage_path,3600);photoUrl=signed.data?.signedUrl??null}setData({vehicle,photoUrl,maintenanceCount:maintenance.count??0,openSymptoms:symptoms.count??0,pendingReminders:reminders.count??0,recentMaintenance:maintenance.data??[]})},[session]);
  useFocusEffect(useCallback(()=>{void load()},[load]));
  if(!data&&!error)return <Screen><View style={styles.loading}><ActivityIndicator color={p.teal}/></View></Screen>;
  if(error)return <Screen><Brand/><PageTitle subtitle={error}>Garage unavailable</PageTitle><Button onPress={()=>void load()}>Try again</Button></Screen>;
  if(!data?.vehicle)return <Screen><Brand/><PageTitle subtitle="Add a vehicle to start a durable maintenance and repair history.">Your garage is ready.</PageTitle><Button onPress={()=>router.push("/onboarding")}>Add your first vehicle</Button></Screen>;
  const vehicle=data.vehicle;const needsAttention=data.openSymptoms>0;const status=needsAttention?"Attention recorded":data.pendingReminders>0?"Service planned":"No open items";
  return <Screen><Brand/><PageTitle subtitle="A concise view of documented needs—not a mechanical diagnosis.">Today in your garage</PageTitle>{data.photoUrl?<Image source={data.photoUrl} style={styles.heroPhoto} contentFit="cover"/>:null}<Panel style={styles.vehiclePanel}><View style={styles.vehicleTop}><View style={styles.vehicleCopy}><Text style={[styles.vehicleName,{color:p.text}]}>{vehicle.year} {vehicle.make} {vehicle.model}</Text><Text style={[styles.trim,{color:p.muted}]}>{vehicle.trim||"Vehicle record"}</Text></View><View style={[styles.status,{backgroundColor:needsAttention?`${p.orange}1f`:p.tealSoft}]}><Text style={[styles.statusText,{color:needsAttention?p.orange:p.teal}]}>{status}</Text></View></View><Divider/><View style={styles.stats}><Stat label="Current mileage" value={vehicle.current_mileage.toLocaleString()}/><Stat label="Open symptoms" value={String(data.openSymptoms)} tone={data.openSymptoms?"orange":"teal"}/><Stat label="Service reminders" value={String(data.pendingReminders)}/></View></Panel>
    <View style={styles.sectionHeading}><Text style={[styles.sectionTitle,{color:p.text}]}>Repair journey</Text><Text style={[styles.sectionCopy,{color:p.muted}]}>Keep every decision connected.</Text></View><View style={[styles.journey,{backgroundColor:p.card,borderColor:p.border}]}>{["Symptom","Shop","Estimate","Repair","Invoice","History"].map((label,index)=><View style={styles.journeyStep} key={label}><View style={[styles.journeyDot,{backgroundColor:index===0?p.amber:p.surface}]}><Text style={styles.journeyNumber}>{index+1}</Text></View><Text style={[styles.journeyLabel,{color:p.muted}]}>{label}</Text></View>)}</View>
    <View style={styles.sectionHeading}><Text style={[styles.sectionTitle,{color:p.text}]}>Recent work</Text><Pressable onPress={()=>router.push("/(tabs)/garage")}><Text style={[styles.link,{color:p.teal}]}>Open garage</Text></Pressable></View>{data.recentMaintenance.length?<Panel>{data.recentMaintenance.map((record,index)=><View key={record.id}>{index?<Divider/>:null}<Text style={[styles.recordTitle,{color:p.text}]}>{record.title}</Text><Text style={[styles.recordMeta,{color:p.muted}]}>{record.performed_at} · {record.cost==null?"Cost not recorded":`$${Number(record.cost).toLocaleString()}`}</Text></View>)}</Panel>:<Panel><Text style={[styles.emptyTitle,{color:p.text}]}>No maintenance recorded yet</Text><Text style={[styles.emptyCopy,{color:p.muted}]}>Your first documented service will appear here and in the vehicle timeline.</Text></Panel>}
  </Screen>}
const styles=StyleSheet.create({loading:{minHeight:500,alignItems:"center",justifyContent:"center"},heroPhoto:{height:240,borderRadius:16,marginBottom:14},vehiclePanel:{padding:20},vehicleTop:{flexDirection:"row",alignItems:"flex-start",justifyContent:"space-between",gap:12},vehicleCopy:{flex:1},vehicleName:{fontSize:23,fontWeight:"800",letterSpacing:-.6},trim:{fontSize:13,marginTop:5},status:{borderRadius:999,paddingVertical:7,paddingHorizontal:10},statusText:{fontSize:11,fontWeight:"800"},stats:{flexDirection:"row",justifyContent:"space-between",gap:12},sectionHeading:{flexDirection:"row",alignItems:"flex-end",justifyContent:"space-between",gap:12,marginTop:28,marginBottom:10},sectionTitle:{fontSize:18,fontWeight:"800"},sectionCopy:{fontSize:12},link:{fontSize:12,fontWeight:"800"},journey:{flexDirection:"row",borderWidth:1,borderRadius:16,padding:16,justifyContent:"space-between",gap:6},journeyStep:{alignItems:"center",flex:1},journeyDot:{width:30,height:30,borderRadius:15,alignItems:"center",justifyContent:"center"},journeyNumber:{fontSize:11,fontWeight:"800",color:"#191c1d"},journeyLabel:{fontSize:9,fontWeight:"700",marginTop:7,textAlign:"center"},recordTitle:{fontSize:14,fontWeight:"700"},recordMeta:{fontSize:12,marginTop:5},emptyTitle:{fontSize:15,fontWeight:"800"},emptyCopy:{fontSize:13,lineHeight:20,marginTop:6}});
