import { useFocusEffect } from "expo-router";
import { useCallback, useState } from "react";
import { ActivityIndicator, Linking, Pressable, StyleSheet, Text, View } from "react-native";
import { Brand, Divider, PageTitle, Panel, Screen } from "@/components/garage-ui";
import { supabase } from "@/lib/supabase";
import { usePalette } from "@/theme";
interface Shop{id:string;name:string;specialty:string|null;address:string|null;phone:string|null}
export default function ShopsScreen(){const p=usePalette();const [shops,setShops]=useState<Shop[]>();const load=useCallback(async()=>{const {data}=await supabase.from("shops").select("id,name,specialty,address,phone").order("name");setShops(data??[])},[]);useFocusEffect(useCallback(()=>{void load()},[load]));return <Screen><Brand/><PageTitle subtitle="Shops stay connected to estimates, repairs, invoices, and your private notes.">Repair shops</PageTitle>{!shops?<View style={styles.loading}><ActivityIndicator color={p.teal}/></View>:shops.length?<Panel>{shops.map((shop,index)=><View key={shop.id}>{index?<Divider/>:null}<Text style={[styles.name,{color:p.text}]}>{shop.name}</Text>{shop.specialty?<Text style={[styles.meta,{color:p.muted}]}>{shop.specialty}</Text>:null}{shop.address?<Text style={[styles.address,{color:p.muted}]}>{shop.address}</Text>:null}{shop.phone?<Pressable accessibilityRole="link" onPress={()=>void Linking.openURL(`tel:${shop.phone}`)}><Text style={[styles.phone,{color:p.teal}]}>{shop.phone}</Text></Pressable>:null}</View>)}</Panel>:<Panel><Text style={[styles.name,{color:p.text}]}>No repair shops saved</Text><Text style={[styles.meta,{color:p.muted}]}>Shops you use will appear here and remain connected to the work they performed.</Text></Panel>}</Screen>}
const styles=StyleSheet.create({loading:{minHeight:320,alignItems:"center",justifyContent:"center"},name:{fontSize:15,fontWeight:"800"},meta:{fontSize:13,marginTop:5,lineHeight:19},address:{fontSize:12,marginTop:7,lineHeight:18},phone:{fontSize:13,fontWeight:"700",marginTop:8,paddingVertical:6}});
