import type { PropsWithChildren } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, type TextInputProps, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { usePalette } from "@/theme";

export function Screen({children,scroll=true}:{children:React.ReactNode;scroll?:boolean}){
  const palette=usePalette();
  const content=<View style={styles.content}>{children}</View>;
  return <SafeAreaView style={[styles.safe,{backgroundColor:palette.canvas}]} edges={["top","left","right"]}>{scroll?<ScrollView contentContainerStyle={styles.scroll} keyboardShouldPersistTaps="handled">{content}</ScrollView>:content}</SafeAreaView>;
}
export function Brand(){const p=usePalette();return <View style={styles.brand}><View style={[styles.brandMark,{backgroundColor:p.amber}]}><View style={[styles.brandLine,{borderColor:"#191c1d"}]}/></View><Text style={[styles.brandText,{color:p.text}]}>GarageBook</Text></View>}
export function PageTitle({children,subtitle}:{children:string;subtitle?:string}){const p=usePalette();return <View style={styles.titleWrap}><Text accessibilityRole="header" style={[styles.title,{color:p.text}]}>{children}</Text>{subtitle?<Text style={[styles.subtitle,{color:p.muted}]}>{subtitle}</Text>:null}</View>}
export function Panel({children,style}:{children:React.ReactNode;style?:object}){const p=usePalette();return <View style={[styles.panel,{backgroundColor:p.card,borderColor:p.border},style]}>{children}</View>}
export function Field({label,error,...props}:{label:string;error?:string}&TextInputProps){const p=usePalette();return <View style={styles.field}><Text style={[styles.label,{color:p.text}]}>{label}</Text><TextInput accessibilityLabel={label} placeholderTextColor={p.muted} style={[styles.input,props.multiline&&styles.textarea,{backgroundColor:p.card,borderColor:error?p.danger:p.border,color:p.text}]} textAlignVertical={props.multiline?"top":undefined} {...props}/>{error?<Text accessibilityRole="alert" style={[styles.error,{color:p.danger}]}>{error}</Text>:null}</View>}
export function ChoiceGroup({label,value,options,onChange}:{label:string;value:string;options:{label:string;value:string}[];onChange:(value:string)=>void}){const p=usePalette();return <View style={styles.choiceField}><Text style={[styles.label,{color:p.text}]}>{label}</Text><View accessibilityRole="radiogroup" style={[styles.choiceGroup,{backgroundColor:p.surface}]}>{options.map(option=>{const selected=option.value===value;return <Pressable accessibilityRole="radio" accessibilityState={{checked:selected}} key={option.value} onPress={()=>onChange(option.value)} style={[styles.choice,{backgroundColor:selected?p.amber:"transparent"}]}><Text style={[styles.choiceText,{color:selected?"#191c1d":p.muted}]}>{option.label}</Text></Pressable>})}</View></View>}
export function Button({children,onPress,busy=false,variant="primary",disabled=false}:{children:string;onPress:()=>void;busy?:boolean;variant?:"primary"|"secondary"|"text";disabled?:boolean}){const p=usePalette();const background=variant==="primary"?p.amber:variant==="secondary"?p.card:"transparent";return <Pressable accessibilityRole="button" disabled={disabled||busy} onPress={onPress} style={({pressed})=>[styles.button,{backgroundColor:background,borderColor:variant==="secondary"?p.border:"transparent",opacity:pressed||disabled?0.6:1}]}>{busy?<ActivityIndicator color="#191c1d"/>:<Text style={[styles.buttonText,{color:variant==="primary"?"#191c1d":p.text}]}>{children}</Text>}</Pressable>}
export function Stat({label,value,tone="default"}:{label:string;value:string;tone?:"default"|"teal"|"orange"}){const p=usePalette();const color=tone==="teal"?p.teal:tone==="orange"?p.orange:p.text;return <View><Text style={[styles.statValue,{color}]}>{value}</Text><Text style={[styles.statLabel,{color:p.muted}]}>{label}</Text></View>}
export function Divider(){const p=usePalette();return <View style={[styles.divider,{backgroundColor:p.border}]}/>}
export function InlineMessage({children,error=false}:PropsWithChildren<{error?:boolean}>){const p=usePalette();return <Text accessibilityRole={error?"alert":undefined} style={[styles.message,{backgroundColor:error?`${p.danger}18`:p.tealSoft,color:error?p.danger:p.teal}]}>{children}</Text>}

const styles=StyleSheet.create({safe:{flex:1},scroll:{flexGrow:1},content:{width:"100%",maxWidth:720,alignSelf:"center",paddingHorizontal:20,paddingTop:14,paddingBottom:120},brand:{flexDirection:"row",alignItems:"center",gap:9},brandMark:{width:28,height:28,borderRadius:9,alignItems:"center",justifyContent:"center"},brandLine:{width:14,height:8,borderWidth:2,borderTopLeftRadius:7,borderTopRightRadius:7},brandText:{fontSize:18,fontWeight:"800",letterSpacing:-.4},titleWrap:{marginTop:28,marginBottom:22},title:{fontSize:34,fontWeight:"800",letterSpacing:-1.1,lineHeight:38},subtitle:{fontSize:15,lineHeight:22,marginTop:8,maxWidth:560},panel:{borderWidth:1,borderRadius:16,padding:18},field:{gap:7,marginBottom:15},label:{fontSize:13,fontWeight:"700"},input:{minHeight:50,borderWidth:1,borderRadius:12,paddingHorizontal:14,fontSize:16},textarea:{minHeight:116,paddingTop:14,paddingBottom:14},choiceField:{gap:7,marginBottom:15},choiceGroup:{flexDirection:"row",borderRadius:12,padding:4,gap:3},choice:{minHeight:42,flex:1,alignItems:"center",justifyContent:"center",borderRadius:9,paddingHorizontal:7},choiceText:{fontSize:12,fontWeight:"800",textAlign:"center"},error:{fontSize:12,lineHeight:17},button:{minHeight:50,borderWidth:1,borderRadius:12,alignItems:"center",justifyContent:"center",paddingHorizontal:18},buttonText:{fontSize:15,fontWeight:"800"},statValue:{fontSize:24,fontWeight:"800",letterSpacing:-.5},statLabel:{fontSize:12,marginTop:3},divider:{height:1,marginVertical:16},message:{overflow:"hidden",borderRadius:10,padding:12,fontSize:13,lineHeight:19,marginBottom:14}});
