import { router, useLocalSearchParams } from "expo-router";
import { useEffect, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { Brand, Button, ChoiceGroup, Field, InlineMessage, PageTitle, Panel, Screen } from "@/components/garage-ui";
import { localDateToday, nativeMaintenanceSchema } from "@/lib/record-validation";
import { supabase } from "@/lib/supabase";
import { useSession } from "@/providers/session-provider";
import { usePalette } from "@/theme";

type RecordType="maintenance"|"repair"|"inspection";
export default function NewMaintenanceScreen(){
  const {id}=useLocalSearchParams<{id:string}>();const {session}=useSession();const p=usePalette();const [type,setType]=useState<RecordType>("maintenance");const [title,setTitle]=useState("");const [date,setDate]=useState(localDateToday());const [mileage,setMileage]=useState("");const [cost,setCost]=useState("0");const [notes,setNotes]=useState("");const [busy,setBusy]=useState(false);const [message,setMessage]=useState<{text:string;error?:boolean}>();
  useEffect(()=>{if(!id)return;void supabase.from("vehicles").select("current_mileage").eq("id",id).maybeSingle().then(({data})=>{if(data)setMileage(String(data.current_mileage))})},[id]);
  async function save(){if(!session||!id)return;const parsed=nativeMaintenanceSchema.safeParse({type,title,date,mileage,cost,notes});if(!parsed.success){setMessage({text:parsed.error.issues[0]?.message??"Check the record details.",error:true});return}setBusy(true);setMessage(undefined);const value=parsed.data;const {data:record,error}=await supabase.from("maintenance_records").insert({owner_id:session.user.id,vehicle_id:id,shop_id:null,record_type:value.type,title:value.title,description:value.notes,performed_at:value.date,mileage:value.mileage,cost:value.cost}).select("id").single();if(error||!record){setMessage({text:"The record could not be saved. Check your connection and try again.",error:true});setBusy(false);return}const mileageResult=await supabase.from("vehicle_mileage_entries").insert({owner_id:session.user.id,vehicle_id:id,mileage:value.mileage,recorded_at:`${value.date}T12:00:00Z`,source:value.type==="repair"?"repair":"maintenance"});if(mileageResult.error){await supabase.from("maintenance_records").delete().eq("id",record.id);setMessage({text:"The record could not be completed because its mileage history failed. Nothing was added; try again.",error:true});setBusy(false);return}router.replace(`/vehicles/${id}`)}
  return <Screen><View style={styles.top}><Brand/><Pressable accessibilityRole="button" onPress={()=>router.back()}><Text style={[styles.cancel,{color:p.teal}]}>Cancel</Text></Pressable></View><PageTitle subtitle="Add completed work and the evidence you know. You can connect a shop or document from the web while native repair tools are completed.">Add maintenance</PageTitle><Panel>{message?<InlineMessage error={message.error}>{message.text}</InlineMessage>:null}<ChoiceGroup label="Record type" value={type} onChange={value=>setType(value as RecordType)} options={[{label:"Maintenance",value:"maintenance"},{label:"Repair",value:"repair"},{label:"Inspection",value:"inspection"}]}/><Field label="Service or repair" autoCapitalize="sentences" placeholder="Front brake pad replacement" value={title} onChangeText={setTitle}/><View style={styles.row}><View style={styles.half}><Field label="Date" autoCapitalize="none" placeholder="YYYY-MM-DD" value={date} onChangeText={setDate}/></View><View style={styles.half}><Field label="Mileage" keyboardType="number-pad" value={mileage} onChangeText={setMileage}/></View></View><Field label="Total cost" keyboardType="decimal-pad" value={cost} onChangeText={setCost}/><Field label="Work performed" multiline placeholder="What work was completed?" value={notes} onChangeText={setNotes}/><Button busy={busy} onPress={save}>Save maintenance record</Button></Panel></Screen>;
}
const styles=StyleSheet.create({top:{flexDirection:"row",alignItems:"center",justifyContent:"space-between"},cancel:{fontSize:13,fontWeight:"800",paddingVertical:10},row:{flexDirection:"row",gap:12},half:{flex:1}});
