import * as ImagePicker from "expo-image-picker";
import { Image } from "expo-image";
import { Redirect, router } from "expo-router";
import { useEffect, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { z } from "zod";
import { Brand, Button, Field, InlineMessage, Panel, Screen } from "@/components/garage-ui";
import { supabase } from "@/lib/supabase";
import { useSession } from "@/providers/session-provider";
import { usePalette } from "@/theme";

const schema=z.object({year:z.coerce.number().int().min(1886).max(new Date().getFullYear()+1),make:z.string().trim().min(2),model:z.string().trim().min(1),trim:z.string().trim().max(80),mileage:z.coerce.number().int().min(0).max(10_000_000)});
interface VehicleDraft {id:string;year:number;make:string;model:string;mileage:number}

export default function OnboardingScreen(){
  const {session,loading}=useSession();const p=usePalette();const [step,setStep]=useState<1|2>(1);const [year,setYear]=useState(String(new Date().getFullYear()));const [make,setMake]=useState("");const [model,setModel]=useState("");const [trim,setTrim]=useState("");const [mileage,setMileage]=useState("0");const [vehicle,setVehicle]=useState<VehicleDraft>();const [photoUri,setPhotoUri]=useState<string>();const [busy,setBusy]=useState(false);const [message,setMessage]=useState<{text:string;error?:boolean}>();
  useEffect(()=>{if(!session)return;void supabase.from("vehicles").select("id,year,make,model,current_mileage").order("created_at").limit(1).maybeSingle().then(({data})=>{if(data)setVehicle({id:data.id,year:data.year,make:data.make,model:data.model,mileage:data.current_mileage})})},[session]);
  if(!loading&&!session)return <Redirect href="/login"/>;
  async function addVehicle(){if(!session)return;const parsed=schema.safeParse({year,make,model,trim,mileage});if(!parsed.success){setMessage({text:"Add a valid year, make, model, and current mileage.",error:true});return}setBusy(true);setMessage(undefined);const value=parsed.data;const {data,error}=await supabase.from("vehicles").insert({owner_id:session.user.id,year:value.year,make:value.make,model:value.model,trim:value.trim||null,current_mileage:value.mileage}).select("id").single();if(error||!data){setMessage({text:"We couldn’t save this vehicle. Check your connection and try again.",error:true});setBusy(false);return}await supabase.from("vehicle_mileage_entries").insert({owner_id:session.user.id,vehicle_id:data.id,mileage:value.mileage,source:"manual"});setVehicle({id:data.id,year:value.year,make:value.make,model:value.model,mileage:value.mileage});setStep(2);setBusy(false)}
  async function addPhoto(){if(!session||!vehicle)return;const permission=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!permission.granted){setMessage({text:"Allow photo-library access to add a vehicle photo.",error:true});return}const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:["images"],allowsEditing:true,quality:.82});if(result.canceled)return;const asset=result.assets[0];setBusy(true);setMessage(undefined);try{const bytes=await fetch(asset.uri).then(response=>response.arrayBuffer());const mimeType=asset.mimeType??"image/jpeg";const extension=mimeType==="image/png"?"png":mimeType==="image/webp"?"webp":"jpg";const fileName=asset.fileName??`vehicle-photo.${extension}`;const path=`${session.user.id}/${vehicle.id}/${Date.now()}-vehicle-photo.${extension}`;const upload=await supabase.storage.from("vehicle-documents").upload(path,bytes,{contentType:mimeType,upsert:false});if(upload.error)throw upload.error;const document=await supabase.from("documents").insert({owner_id:session.user.id,vehicle_id:vehicle.id,document_type:"photo",storage_path:path,file_name:fileName,mime_type:mimeType,file_size_bytes:bytes.byteLength});if(document.error){await supabase.storage.from("vehicle-documents").remove([path]);throw document.error}setPhotoUri(asset.uri);setMessage({text:"Vehicle photo saved privately."})}catch{setMessage({text:"The photo could not be uploaded. Try a smaller JPG, PNG, or WebP image.",error:true})}finally{setBusy(false)}}
  async function finish(){setBusy(true);const {error}=await supabase.auth.updateUser({data:{onboarding_completed:true}});if(error){setMessage({text:"We couldn’t finish setup. Try again.",error:true});setBusy(false);return}router.replace("/(tabs)")}
  async function skip(){await supabase.auth.updateUser({data:{onboarding_completed:true}});router.replace("/(tabs)")}
  return <Screen><View style={styles.top}><Brand/><Pressable onPress={skip} accessibilityRole="button"><Text style={[styles.skip,{color:p.teal}]}>Skip for now</Text></Pressable></View><View style={styles.progress}><View style={[styles.dot,{backgroundColor:step>=1?p.amber:p.surface}]}><Text style={styles.dotText}>1</Text></View><View style={[styles.line,{backgroundColor:p.border}]}/><View style={[styles.dot,{backgroundColor:step===2?p.amber:p.surface}]}><Text style={styles.dotText}>2</Text></View></View>
    {step===1?<><Text style={[styles.heading,{color:p.text}]}>Give this vehicle an honest starting point.</Text><Text style={[styles.copy,{color:p.muted}]}>Older vehicles rarely arrive with perfect history. Current mileage is enough to begin; unknown history can stay unknown.</Text><Panel style={styles.panel}>{message?<InlineMessage error={message.error}>{message.text}</InlineMessage>:null}<View style={styles.row}><View style={styles.half}><Field label="Model year" keyboardType="number-pad" value={year} onChangeText={setYear}/></View><View style={styles.half}><Field label="Current mileage" keyboardType="number-pad" value={mileage} onChangeText={setMileage}/></View></View><Field label="Make" autoCapitalize="words" value={make} onChangeText={setMake}/><Field label="Model" autoCapitalize="words" value={model} onChangeText={setModel}/><Field label="Trim (optional)" autoCapitalize="words" value={trim} onChangeText={setTrim}/><Button busy={busy} onPress={addVehicle}>Add vehicle and continue</Button>{vehicle?<Button variant="text" onPress={()=>setStep(2)}>{`Continue with ${vehicle.year} ${vehicle.make} ${vehicle.model}`}</Button>:null}</Panel></>:<><Text style={[styles.heading,{color:p.text}]}>Record what is true today.</Text><Text style={[styles.copy,{color:p.muted}]}>A current photo creates the first visual anchor. You can add maintenance, symptoms, and reminders next.</Text><Panel style={styles.panel}>{message?<InlineMessage error={message.error}>{message.text}</InlineMessage>:null}{vehicle?<View style={styles.vehicle}><Text style={[styles.vehicleTitle,{color:p.text}]}>{vehicle.year} {vehicle.make} {vehicle.model}</Text><Text style={[styles.vehicleMileage,{color:p.teal}]}>{vehicle.mileage.toLocaleString()} miles</Text></View>:null}{photoUri?<Image source={photoUri} style={styles.photo} contentFit="cover"/>:<View style={[styles.photoEmpty,{backgroundColor:p.surface}]}><Text style={[styles.photoEmptyText,{color:p.muted}]}>Your private vehicle photo will appear here.</Text></View>}<Button busy={busy} variant="secondary" onPress={addPhoto}>{photoUri?"Choose a different photo":"Add a vehicle photo"}</Button><View style={styles.finish}><Button busy={busy} onPress={finish}>Finish and open dashboard</Button></View></Panel></>}
  </Screen>;
}
const styles=StyleSheet.create({top:{flexDirection:"row",alignItems:"center",justifyContent:"space-between"},skip:{fontSize:13,fontWeight:"700",padding:10},progress:{flexDirection:"row",alignItems:"center",width:126,marginTop:38,marginBottom:24},dot:{width:30,height:30,borderRadius:15,alignItems:"center",justifyContent:"center"},dotText:{color:"#191c1d",fontSize:12,fontWeight:"800"},line:{height:1,flex:1},heading:{fontSize:36,lineHeight:40,fontWeight:"800",letterSpacing:-1.2,maxWidth:560},copy:{fontSize:15,lineHeight:23,maxWidth:600,marginTop:12,marginBottom:24},panel:{maxWidth:620},row:{flexDirection:"row",gap:12},half:{flex:1},vehicle:{marginBottom:16},vehicleTitle:{fontSize:20,fontWeight:"800"},vehicleMileage:{fontSize:14,fontWeight:"700",marginTop:5},photo:{height:240,borderRadius:13,marginBottom:14},photoEmpty:{height:180,borderRadius:13,alignItems:"center",justifyContent:"center",padding:30,marginBottom:14},photoEmptyText:{fontSize:13,textAlign:"center",lineHeight:20},finish:{marginTop:12}});
