import Link from "next/link";
import { AlertTriangle, FileUp, Gauge, Plus, Wrench } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { PageHeader } from "@/components/page-header";
import { VehicleTimeline } from "@/components/timeline";
import { formatCurrency, formatMileage, sampleVehicle, timelineEvents } from "@/lib/sample-data";

export default function VehiclePage(){return <AppShell><PageHeader eyebrow="My garage" title={`${sampleVehicle.year} ${sampleVehicle.make} ${sampleVehicle.model}`} description={`${sampleVehicle.trim} · ${sampleVehicle.color} · VIN ${sampleVehicle.vin}`} actions={<><Link className="btn btn-secondary" href={`/vehicles/${sampleVehicle.id}/symptoms/new`}><AlertTriangle size={16}/>Log symptom</Link><Link className="btn btn-primary" href={`/vehicles/${sampleVehicle.id}/maintenance/new`}><Plus size={16}/>Add record</Link></>}/><section className="mb-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Stat label="Current mileage" value={`${formatMileage(sampleVehicle.mileage)} mi`} icon={Gauge}/><Stat label="Vehicle health" value={`${sampleVehicle.healthScore} · ${sampleVehicle.healthLabel}`} icon={Wrench}/><Stat label="Lifetime spend" value={formatCurrency(sampleVehicle.totalSpend)} icon={FileUp}/><Stat label="Records" value={`${timelineEvents.length} events`} icon={Plus}/></section><section className="grid gap-7 lg:grid-cols-[1fr_260px]"><div><div className="mb-5"><h2 className="text-xl font-semibold">Vehicle timeline</h2><p className="mt-1 text-sm text-muted">One chronological record of service, symptoms, visits, and documents.</p></div><VehicleTimeline events={timelineEvents}/></div><aside className="space-y-4 lg:sticky lg:top-24 lg:self-start"><div className="card p-5"><h3 className="font-semibold">Vehicle details</h3><dl className="mt-4 space-y-3 text-sm"><Row label="Model year" value="2014"/><Row label="Trim" value={sampleVehicle.trim}/><Row label="Drivetrain" value="All-wheel drive"/><Row label="Engine" value="1.6L Turbo I4"/><Row label="Fuel" value="Premium gasoline"/></dl></div><div className="card p-5"><h3 className="font-semibold">Documents</h3><p className="mt-2 text-sm text-muted">12 invoices, receipts, and photos</p><button className="btn btn-secondary mt-4 w-full"><FileUp size={16}/>Upload document</button></div></aside></section></AppShell>}
function Stat({label,value,icon:Icon}:{label:string;value:string;icon:React.ComponentType<{size?:number}>}){return <div className="card p-5"><Icon className="text-teal" size={18}/><p className="mt-4 text-xs text-muted">{label}</p><p className="mt-1 font-semibold">{value}</p></div>};
function Row({label,value}:{label:string;value:string}){return <div className="flex justify-between gap-3"><dt className="text-muted">{label}</dt><dd className="text-right font-medium">{value}</dd></div>}
